export const queryKeys = {
  heroHeadIcons: ['config', 'heroHeadIcons'] as const,
  heroTypeDesc: ['config', 'HeroTypeDescConfig'] as const,
  equipmentCatalogRaw: ['catalog', 'equipment', 'raw'] as const,
  catalogCounts: ['catalog', 'counts'] as const,
  heroTalents: (heroId: number, lang: string) => ['hero', heroId, 'talents', lang] as const,
  heroCosmo: (heroId: number, lang: string) => ['hero', heroId, 'cosmo', lang] as const,
  heroOverview: (heroId: number, lang: string) => ['hero', heroId, 'overview', lang] as const,
  stageUpLadders: ['config', 'stageUpLadders'] as const,
  stageUpCatalog: ['catalog', 'stageUpHeroes'] as const,
  stageUpHero: (heroId: number, lang: string) => ['hero', heroId, 'stageUp', lang] as const,
  itemCatalog: ['catalog', 'items'] as const,
  itemDetail: (itemId: number, lang: string) => ['item', itemId, 'detail', lang] as const,
  itemUsage: (itemId: number) => ['item', itemId, 'usage'] as const,
  dbChangelog: ['changelog', 'db', 'v3'] as const,
}
